---
title: "206_Final_ClaireMadden"
author: "Claire Madden"
date: "12/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo = FALSE}

library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(effsize)
library(corrplot)
library(car)
library(stargazer)

```

```{r read in data, echo = FALSE, message = FALSE}
pesticide_residues <- read_csv("PesticideResidues.csv")

ca_county_pesticides <- read_csv("ca_county_pesticides.csv")

climate_opinion <- read_csv("climate_opinion.csv")

tmas_df <- read_csv("tmas_df.csv")

ucsb_climate <- read_csv("ucsb_climate.csv")


```


###PART 1.
```{r part 1 instructions}
#Explore relationships between climate change perspectives, information exposure, education attainment, poverty levels and coastline on the proportion of people who believe that global warming is happening (i.e., ‘happening’ should be your dependent variable). in climate_opinion dataframe

#happening: Estimated percentage in state who think that global warming is happening
#consensus: Estimated percentage who believe that most scientists think global warming is happening
#discuss: Estimated percentage who discuss global warming occassionally or often with friends and family
#mediaweekly: Estimated percentage who hear about global warming in the media at least weekly
#bachelors*: Estimated percentage (25 years and older) attained Bachelor’s degree
#poverty*: Estimated poverty rate (by household income)
#coastline: yes = state has ocean coastline, no = state does not have ocean coastline

```


```{r 1a}
#a. A brief statement (1-sentence) explaining the type of analysis you chose to perform, and why it is appropriate.
# multiple linear regression
# the dependent variable (proportion of people who believe global warming is happening is dependent on multiple other variables like... )
```


```{r 1b}
#b. An exploratory correlation matrix for all continuous variables (make it readable, but it does not need to be finalized and you do not need to add a figure caption).

cor_df <- cor(climate_opinion[2:7])

corrplot(cor_df,
         type = "upper",
         method = "ellipse",
         tl.col = "black",
         tl.cex = 0.5)

col_df <- climate_opinion %>% 
  select(consensus, discuss, mediaweekly, bachelors)

pairs(col_df)
# consensus and discuss seem to be pretty correllated 

```




```{r 1models}
#saturated model
climate_lm <- lm(happening ~ consensus + discuss + mediaweekly + bachelors + poverty_rate + coastline, data = climate_opinion)

summary(climate_lm)
#mediaweekly has negative coefficient which seems misleading

#model -discuss
climate_lm_1 <- lm(happening ~ consensus + mediaweekly + bachelors + poverty_rate + coastline, data = climate_opinion)

summary(climate_lm_1)
#mediaweekly still negative


#model -consensus
climate_lm_2 <- lm (happening ~ discuss + mediaweekly + bachelors + poverty_rate + coastline, data = climate_opinion)

summary(climate_lm_2)
#mediaweekly still negative

#model -discuss -consensus
climate_lm_3 <- lm(happening ~ bachelors + poverty_rate + coastline, data = climate_opinion)

summary(climate_lm_3)
#maybe took out too many variables

climate_lm_4 <- lm(happening ~ bachelors + poverty_rate + coastline + mediaweekly, data = climate_opinion)

summary(climate_lm_4)
# all coefficients seem to make sense, all significant


vif(climate_lm)
# consensus and discuss are both very high
vif(climate_lm_1)
# consensus still high
vif(climate_lm_2)
# discuss is a bit high
vif(climate_lm_3)
# no concerning vif values
vif(climate_lm_4)
# all seem good

AIC(climate_lm) #122.45
AIC(climate_lm_1) #136.56
AIC(climate_lm_2) #212.61
AIC(climate_lm_3) #249.83
AIC(climate_lm_4) #243.07
```


```{r 1c, results = 'asis', header = FALSE, echo = FALSE}
#c. A finalized table of results for your analyses (you may present more than one model), with a figure caption.

lm_table <- stargazer(climate_lm, 
          type = 'html', 
          digits = 3,
          style = "aer",
          title = "Table X: Climate Opinion Regression Results", 
          dep.var.labels = c("happening"),
          covariate.labels = c("no"))


lm_table
```


```{r 1d}
#d. Choose two coefficients in the model that you find interesting (either because they are expected or unexpected). For each, write a single sentence explaining what that coefficient means in terms of an expected change in the dependent variable.

```



```{r}
#e. Based on diagnostic plots, describe (1 - 2 sentences) if you have concerns about heteroscedasticity or normality of residuals for your model(s). You do not need to include the diagnostic plots in your final document.

plot(climate_lm)
# heteroscedasticity seems good on these ones

plot(climate_lm_4)
# also seems legit - well distributed no obvious issues with heteroscedasticity


```


###PART 2.
```{r}
#Explore associations between race/ethnicity and perceived campus respect based on counts in ‘ucsb_climate.csv.’

#a. In 1 - 2 sentences: What type of analysis will you perform? In the context of this task, what research question will your analysis answer?

#b. A one sentence finalized statement of the statistical results for the analysis you decided on in (a). You are not expected to do post-hoc testing, but you can if you want to.

#c. A finalized figure or table that clearly shows counts and/or proportions of respondents’ perceptions of campus respect for each race/ethnicity reporting. Include a caption.

#d. A concise 2 - 3 sentence discussion of interesting differences and/or similarities across groups, and notable big picture trends.


```



###PART 3. 
```{r}
#explore effects of sex and age on probability that a person will respond True or False to the statement: “I am usually self-conscious.” Data in ‘tmas_df.csv’ are accessed and updated from openpsychometrics.org (a cool site for open-source survey data).
#a. A finalized table of model results and statistics. Include a table caption.
#b. A finalized graph showing predicted probabilities for True/False responses, separated by sex over a range of ages, with standard errors included. You do NOT need to include a figure caption.
#c. In 2 - 3 sentences, describe trends/differences/similarities that are seen in the graph, and how those align with the results you report in (a).




```



###PART 4.
```{r}
#Is there a significant difference in pyraclostrobin concentrations in strawberries (STRAWBERRY (ALL OR UNSPEC)) and carrots (CARROTS (ROOT CROP))? use PesticideResidues dataframe
#a. Summarize/describe any exploratory analyses that you performed in order to decide on the appropriate test to compare concentrations. Include exploratory graphs that informed your decision (you don’t need to finalize or include figure captions here). Based on those outcomes, justify your choice of test.
#b. In 1-2 sentences, state your final results in a format that would be suitable for publication in a professional report or article.

# simplify dataframe to include only the commodities and pesticide of interest
pesticide_simple <- pesticide_residues %>% 
  filter(commodity == "STRAWBERRY (ALL OR UNSPEC)" |
           commodity == "CARROTS (ROOT CROP)") %>% 
  filter(chemical_detected == "PYRACLOSTROBIN")

# explore the distribution of the data
exp_hist <- ggplot(pesticide_simple, aes(x = amount_detected))+
  geom_histogram(bins = 10)+
  facet_wrap(~commodity)


exp_hist
# doesn't look like a normal distribution
# carrots only have 15 observations
# strawberries have 40 observations


exp_qq <- ggplot(pesticide_simple, aes(sample = amount_detected))+
  geom_qq()+
  facet_wrap(~commodity)

exp_qq
# very much not normal looking
# will go with a Mann Whitney U test (????)



carrots <- pesticide_simple %>% 
  filter(commodity == "CARROTS (ROOT CROP)")


strawberries <- pesticide_simple %>% 
  filter(commodity == "STRAWBERRY (ALL OR UNSPEC)")



test <- wilcox.test(strawberries$amount_detected, carrots$amount_detected)

test

# there is a significant difference in median amount of pesticide detected between strawberries and carrots
# p < 0.001


cliffs <- cliff.delta(strawberries$amount_detected, carrots$amount_detected)

cliffs


# cliff's delta = 0.695 (large)
```


###PART 5. 
```{r}
#prepare a final graph (you choose what type) of the top 10 California counties ranked by pounds of active pesticide ingredient applied per square mile. use ca_county_pesticides
#1. Any code used to wrangle the data and prepare your final graph.
#2. Your beautifully finalized graph of the top 10 California counties (by pesticide applied per square mile). You do not need to include a figure caption.

# create a new dataframe with a column that calculates pesticide per square mile
# arrange from highest to lowest pesticide per square mile
# keep only the top 10
pesticide_df <- ca_county_pesticides %>% 
  mutate(pounds_per_mile = pounds_active/area) %>% 
  arrange(-pounds_per_mile) %>% 
  head(10)

# keep current levels so the graph doesnt reorder county alphabetically but order is based on highest to lowest pesticide per square mile 

pesticide_factor <- pesticide_df %>% 
  mutate(county = factor(county, levels = county))
  

# create a column graph!
pesticide_graph <- ggplot(pesticide_factor, aes(x = county, y = pounds_per_mile))+
  geom_col(aes(fill = county), show.legend = FALSE)+
  scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,9000),
                     breaks = seq(0,9000, by = 1000))+
  theme(axis.text.x = element_text(angle = 45, hjust = .9))+
  labs(x = "County",
       y = "Pesticide Applied \n(pounds/square mile)",
       title = "10 California Counties with the \nHighest Pesticide Application per Square Mile")


  
pesticide_graph

```


